(() => {
  const form=document.querySelector('[data-guanshi-consult-form]'); if(!form)return;
  const output=document.querySelector('[data-consult-output]'),pre=document.querySelector('[data-consult-summary]'),copyBtn=document.querySelector('[data-copy-summary]'),submitBtn=form.querySelector('button[type="submit"]'),outputTitle=output?.querySelector('h3'),privacyNote=document.querySelector('.privacy-note');
  const mode=document.body.dataset.consultMode||'general',pageOpenedAt=Date.now(),LAST_KEY='runlu_guanshi_last_consultation';
  const AI=Object.freeze({endpoint:'https://ekrnknlawekeoszzkamd.supabase.co/functions/v1/runlu-guanshi-ai',anonKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6ImVrcm5rbmxhd2VrZW9zenprYW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1OTkxNTMsImV4cCI6MjEwMDE3NTE1M30.MypEa1JShRDE2GqDpNooR1ZmWhkTCDWy22TIjCoNM9w'});
  const i18n={
    en:{titleGeneral:'RUNLU GUANSHI · Consultation',titleTraditional:'RUNLU GUANSHI · Traditional Consultation',generated:'Generated',route:'Route',routeGeneral:'Start GUANSHI · question first',routeTraditional:'Traditional View · method first',input:'INPUT BRIEF',result:'GUANSHI RESULT',chart:'CALENDAR / FOUR PILLARS LAYER',structure:'FIXED TRADITIONAL STRUCTURE',year:'Year pillar',month:'Month pillar',day:'Day pillar',hour:'Hour pillar',dayMaster:'Day Master',chartNote:'Calendar calculation uses the civil date and time entered. No true-solar-time or historical timezone correction is applied; boundary conventions may differ by school.',seed:'Cast seed',line:'Line',moving:'Changing lines',primary:'Primary hexagram',relating:'Relating hexagram',upper:'upper',lower:'lower',moment:'Frozen moment',lunar:'Lunar / branch inputs',arithmetic:'Arithmetic',orientation:'Orientation calculation',sector:'8-sector',mountain:'24-mountain',methodRule:'Fixed rule',note:'Boundary note',noteGeneral:'Reality and reliable evidence remain the primary basis for practical recommendations. Traditional lenses are optional.',noteTraditional:'Traditional interpretation is recorded separately from deterministic mechanics and factual claims. Practical decisions still return to reality and reliable evidence.',thinking:'GUANSHI is calculating first, then analyzing…',copied:'Copied',copy:'Copy full consultation',validate:'Freeze for later review',submitGeneral:'Generate GUANSHI result',submitTraditional:'Generate Traditional View result',outputGeneral:'Your GUANSHI consultation result',outputTraditional:'Your Traditional View consultation result',quota:n=>`Free analyses remaining today: ${n}`,limits:{identity_daily_limit:'You have used today’s two free GUANSHI analyses.',network_daily_limit:'This network has reached today’s free-use limit.',daily_budget_reached:'GUANSHI has reached today’s protected AI budget.',global_hourly_limit:'GUANSHI is temporarily at its hourly capacity.',too_fast:'Please wait a little before generating another result.',duplicate_request:'The same request was just submitted. Please wait before running it again.',too_fast_client:'Please allow the page to finish loading before submitting.'},privacy:'Privacy V1.6: consultation fields are processed server-side for this analysis. Fixed chart/cast/site mechanics are returned with the result. A frozen validation case remains local-first unless you export it.'},
    zh:{titleGeneral:'RUNLU GUANSHI · 观势咨询',titleTraditional:'RUNLU GUANSHI · 传统观势咨询',generated:'生成时间',route:'咨询入口',routeGeneral:'开始观势 · 先问事',routeTraditional:'传统观势 · 先定方法',input:'输入摘要',result:'观势结果',chart:'历法 / 四柱计算层',structure:'固定传统结构',year:'年柱',month:'月柱',day:'日柱',hour:'时柱',dayMaster:'日主',chartNote:'四柱按输入的民用出生日期与时间计算；当前未做真太阳时或历史时区修正，边界时刻不同流派也可能存在差异。',seed:'起卦种子',line:'第',moving:'动爻',primary:'主卦',relating:'变卦',upper:'上卦',lower:'下卦',moment:'冻结时刻',lunar:'农历 / 地支输入',arithmetic:'起卦算式',orientation:'朝向计算',sector:'八方位',mountain:'二十四山',methodRule:'固定规则',note:'边界说明',noteGeneral:'现实与可靠证据始终是实际建议的首要依据；传统观察层为可选项。',noteTraditional:'传统解释与确定性计算、事实判断分账记录；涉及现实决策时，仍以现实条件与可靠证据为主。',thinking:'观势正在先计算，再分析……',copied:'已复制',copy:'复制完整咨询',validate:'冻结为验证案例',submitGeneral:'生成观势结果',submitTraditional:'生成传统观势结果',outputGeneral:'你的观势咨询结果',outputTraditional:'你的传统观势咨询结果',quota:n=>`今日免费观势还可使用：${n} 次`,limits:{identity_daily_limit:'今天的 2 次免费观势已经用完，明天再来吧。',network_daily_limit:'当前网络今天的免费观势额度已经达到上限。',daily_budget_reached:'观势今天的受保护 AI 总预算已经达到上限，明天自动恢复。',global_hourly_limit:'当前一小时内咨询较多，请稍后再试。',too_fast:'两次生成间隔太短，请稍等一会儿再试。',duplicate_request:'刚刚已经提交过相同问题，请稍后再运行。',too_fast_client:'请等页面加载完成后再提交。'},privacy:'V1.6 隐私说明：咨询资料会发送到服务器端用于本次分析；固定排盘、起卦和场地计算会随结果一并返回。冻结后的验证案例正文仍默认只保存在当前浏览器，除非你自己导出。'},
    fr:{titleGeneral:'RUNLU GUANSHI · Consultation',titleTraditional:'RUNLU GUANSHI · Consultation traditionnelle',generated:'Généré',route:'Parcours',routeGeneral:'Commencer GUANSHI · question d’abord',routeTraditional:'Vue traditionnelle · méthode d’abord',input:'RÉSUMÉ DES DONNÉES',result:'RÉSULTAT GUANSHI',chart:'COUCHE CALENDAIRE / QUATRE PILIERS',structure:'STRUCTURE TRADITIONNELLE FIGÉE',year:'Pilier de l’année',month:'Pilier du mois',day:'Pilier du jour',hour:'Pilier de l’heure',dayMaster:'Maître du jour',chartNote:'Le calcul utilise la date et l’heure civiles saisies, sans correction du temps solaire vrai ni du fuseau historique ; les conventions peuvent varier selon les écoles.',seed:'Graine du tirage',line:'Ligne',moving:'Lignes mobiles',primary:'Hexagramme principal',relating:'Hexagramme transformé',upper:'supérieur',lower:'inférieur',moment:'Instant figé',lunar:'Données lunaires / branches',arithmetic:'Calcul',orientation:'Calcul d’orientation',sector:'Secteur 8 directions',mountain:'24 montagnes',methodRule:'Règle fixe',note:'Limite',noteGeneral:'La réalité et les preuves fiables restent la base principale des recommandations pratiques.',noteTraditional:'L’interprétation traditionnelle est séparée des calculs déterministes et des faits ; pour l’action, réalité et preuves fiables restent prioritaires.',thinking:'GUANSHI calcule d’abord, puis analyse…',copied:'Copié',copy:'Copier la consultation complète',validate:'Figer pour révision',submitGeneral:'Générer le résultat GUANSHI',submitTraditional:'Générer le résultat traditionnel',outputGeneral:'Votre résultat GUANSHI',outputTraditional:'Votre résultat traditionnel',quota:n=>`Analyses gratuites restantes aujourd’hui : ${n}`,limits:{identity_daily_limit:'Vos deux analyses gratuites du jour ont été utilisées.',network_daily_limit:'Ce réseau a atteint sa limite gratuite du jour.',daily_budget_reached:'Le budget IA protégé de GUANSHI est atteint pour aujourd’hui.',global_hourly_limit:'GUANSHI est temporairement à sa capacité horaire.',too_fast:'Veuillez patienter avant de générer un autre résultat.',duplicate_request:'La même demande vient d’être envoyée. Veuillez patienter.',too_fast_client:'Veuillez attendre la fin du chargement avant d’envoyer.'},privacy:'Confidentialité V1.6 : les données sont traitées côté serveur ; les calculs fixes sont renvoyés avec le résultat. Un cas figé reste local au navigateur sauf export.'},
    es:{titleGeneral:'RUNLU GUANSHI · Consulta',titleTraditional:'RUNLU GUANSHI · Consulta tradicional',generated:'Generado',route:'Ruta',routeGeneral:'Empezar GUANSHI · primero la pregunta',routeTraditional:'Vista tradicional · primero el método',input:'RESUMEN DE ENTRADA',result:'RESULTADO GUANSHI',chart:'CAPA CALENDÁRICA / CUATRO PILARES',structure:'ESTRUCTURA TRADICIONAL FIJA',year:'Pilar del año',month:'Pilar del mes',day:'Pilar del día',hour:'Pilar de la hora',dayMaster:'Maestro del día',chartNote:'El cálculo usa la fecha y hora civil introducidas, sin corrección de tiempo solar verdadero ni zona horaria histórica; las convenciones pueden variar según la escuela.',seed:'Semilla',line:'Línea',moving:'Líneas móviles',primary:'Hexagrama principal',relating:'Hexagrama transformado',upper:'superior',lower:'inferior',moment:'Momento congelado',lunar:'Datos lunares / ramas',arithmetic:'Cálculo',orientation:'Cálculo de orientación',sector:'Sector de 8 direcciones',mountain:'24 montañas',methodRule:'Regla fija',note:'Límite',noteGeneral:'La realidad y la evidencia fiable siguen siendo la base principal de las recomendaciones prácticas.',noteTraditional:'La interpretación tradicional se separa de los cálculos deterministas y los hechos; para actuar, realidad y evidencia fiable siguen siendo prioritarias.',thinking:'GUANSHI primero calcula y después analiza…',copied:'Copiado',copy:'Copiar consulta completa',validate:'Congelar para revisión',submitGeneral:'Generar resultado GUANSHI',submitTraditional:'Generar resultado tradicional',outputGeneral:'Tu resultado GUANSHI',outputTraditional:'Tu resultado tradicional',quota:n=>`Análisis gratuitos restantes hoy: ${n}`,limits:{identity_daily_limit:'Ya utilizaste los dos análisis gratuitos de hoy.',network_daily_limit:'Esta red alcanzó el límite gratuito de hoy.',daily_budget_reached:'GUANSHI alcanzó hoy su presupuesto de IA protegido.',global_hourly_limit:'GUANSHI está temporalmente en su capacidad horaria.',too_fast:'Espera un poco antes de generar otro resultado.',duplicate_request:'La misma solicitud acaba de enviarse. Espera antes de repetirla.',too_fast_client:'Espera a que termine de cargar la página antes de enviar.'},privacy:'Privacidad V1.6: los datos se procesan en el servidor; los cálculos fijos vuelven con el resultado. Un caso congelado permanece local salvo exportación.'}
  };

  const clean=v=>(v||'').toString().trim(),cap=s=>s.charAt(0).toUpperCase()+s.slice(1),lang=()=>document.querySelector('[data-runlu-language-select]')?.value||localStorage.getItem('runlu_site_language')||'en',labelFor=el=>el?.tagName==='SELECT'?clean(el.options[el.selectedIndex]?.textContent):clean(el?.value),row=(name,value)=>value?`${name}: ${value}`:'';
  function deviceId(){const key='runlu_guanshi_device_id';let id=localStorage.getItem(key)||'';if(!/^[A-Za-z0-9_-]{16,100}$/.test(id)){id=(crypto.randomUUID?.()||`g${Date.now()}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`).replace(/[^A-Za-z0-9_-]/g,'_');localStorage.setItem(key,id);}return id;}
  const trap=document.createElement('input');trap.type='text';trap.name='website';trap.autocomplete='off';trap.tabIndex=-1;trap.setAttribute('aria-hidden','true');trap.style.cssText='position:absolute!important;left:-10000px!important;width:1px!important;height:1px!important;opacity:0!important;';form.appendChild(trap);

  function syncMethodPanels(){
    if(mode!=='traditional')return;
    const method=form.elements.method?.value||'bazi';
    document.querySelectorAll('[data-method-panel]').forEach(panel=>{
      const active=(panel.dataset.methodPanel||'').split(',').includes(method); panel.hidden=!active;
      panel.querySelectorAll('input,select,textarea').forEach(el=>{el.disabled=!active;});
    });
    const bd=form.elements.birth_date, horizon=form.elements.event_horizon;
    if(bd) bd.required=method==='bazi';
    if(horizon) horizon.required=method==='liuyao'||method==='meihua';
  }

  function buildGeneral(data){const lines=[],f=n=>form.elements[n];lines.push(row(f('topicLabel')?.dataset.currentLabel||'Topic',labelFor(f('topic'))));lines.push(row(f('question')?.dataset.summaryLabel||'Question',clean(data.get('question'))));lines.push(row(f('horizonLabel')?.dataset.currentLabel||'Time horizon',labelFor(f('horizon'))));lines.push(row(f('options')?.dataset.summaryLabel||'Options / alternatives',clean(data.get('options'))));lines.push(row(f('facts')?.dataset.summaryLabel||'Known facts',clean(data.get('facts'))));lines.push(row(f('constraints')?.dataset.summaryLabel||'Constraints',clean(data.get('constraints'))));lines.push(row(f('stakesLabel')?.dataset.currentLabel||'Stakes',labelFor(f('stakes'))));lines.push(row(f('traditionalLabel')?.dataset.currentLabel||'Traditional lens',labelFor(f('traditional'))));return lines.filter(Boolean);}
  function buildTraditional(data){
    const lines=[],f=n=>form.elements[n],skip=new Set(['method','topic','question','boundary','website']);
    lines.push(row(f('methodLabel')?.dataset.currentLabel||'Traditional method',labelFor(f('method'))));
    lines.push(row(f('topicLabel')?.dataset.currentLabel||'Topic',labelFor(f('topic'))));
    lines.push(row(f('question')?.dataset.summaryLabel||'Question',clean(data.get('question'))));
    for(const[name,value]of data.entries()){
      if(skip.has(name)||name.endsWith('Label'))continue; const el=f(name); if(!el)continue;
      const shown=el.tagName==='SELECT'?labelFor(el):clean(value); if(!shown)continue;
      const label=el.dataset.summaryLabel||document.querySelector(`label[for="${CSS.escape(name)}"]`)?.textContent?.trim()||name.replaceAll('_',' '); lines.push(row(label,shown));
    }
    return lines.filter(Boolean);
  }
  function payloadFields(data){const fields={};for(const[name,value]of data.entries()){if(name==='boundary'||name==='website'||name.endsWith('Label'))continue;fields[name]=clean(value).slice(0,2200);const el=form.elements[name];if(el?.tagName==='SELECT')fields[`${name}_label`]=labelFor(el).slice(0,500);}return fields;}
  function localDate(){const d=new Date(),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
  function localDateTime(){const d=new Date(),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;}
  function timezoneName(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'';}catch{return'';}}
  function chartText(chart,t){if(!chart||chart.error||!chart.four_pillars)return'';const p=chart.four_pillars;return[`【${t.chart}】`,`${t.year}: ${p.year}`,`${t.month}: ${p.month}`,`${t.day}: ${p.day}`,`${t.hour}: ${p.hour}`,`${t.dayMaster}: ${chart.day_master||''}`,t.chartNote,''].join('\n');}
  function hexText(h,t){if(!h)return'';return`#${h.number} ${h.name_zh||''} · ${t.upper}: ${h.upper?.zh||''} ${h.upper?.en||''} · ${t.lower}: ${h.lower?.zh||''} ${h.lower?.en||''}`;}
  function structureText(s,t){
    if(!s||!s.kind)return''; const lines=[`【${t.structure}】`];
    if(s.kind==='liuyao'){
      lines.push(`${t.methodRule}: ${s.method_version}`,`${t.seed}: ${s.seed}`);
      (s.line_values_bottom_to_top||[]).forEach((v,i)=>lines.push(`${t.line} ${i+1}: ${(s.coin_faces?.[i]||[]).join(' ')} = ${v}${(v===6||v===9)?' *':''}`));
      lines.push(`${t.moving}: ${(s.changing_lines||[]).length?(s.changing_lines||[]).join(', '):'—'}`,`${t.primary}: ${hexText(s.primary,t)}`); if(s.relating)lines.push(`${t.relating}: ${hexText(s.relating,t)}`); lines.push(s.audit_note||'');
    }else if(s.kind==='meihua'){
      const l=s.lunar_basis||{},a=s.arithmetic||{};
      lines.push(`${t.methodRule}: ${s.method_version}`,`${t.moment}: ${s.moment_basis} · ${s.timezone_name||''} · UTC offset ${s.timezone_offset_minutes??''} min`,`${t.lunar}: ${l.year_ganzhi||''}; year branch ${l.year_branch||''}=${l.year_branch_ordinal??''}; month ${l.month??''}${l.is_leap_month?' (leap)':''}; day ${l.day??''}; hour branch no. ${l.hour_branch_ordinal??''}`,`${t.arithmetic}:`,a.upper||'',a.lower||'',a.moving_line||'',`${t.moving}: ${s.moving_line}`,`${t.primary}: ${hexText(s.primary,t)}`,`${t.relating}: ${hexText(s.relating,t)}`,s.audit_note||'');
    }else if(s.kind==='fengshui_site'){
      lines.push(`${t.methodRule}: ${s.method_version}`); if(s.orientation)lines.push(`${t.orientation}: ${s.orientation.facing_degrees}° · ${s.orientation.basis||''}`,`${t.sector}: ${s.orientation.sector_8?.zh||''} / ${s.orientation.sector_8?.en||''}`,`${t.mountain}: ${s.orientation.mountain_24||''}`); else lines.push(`${t.orientation}: —`); lines.push(s.audit_note||'');
    }
    lines.push(''); return lines.filter(v=>v!==undefined&&v!==null).join('\n');
  }
  function authToken(){const live=window.RUNLU_AUTH?.accessToken;return typeof live==='string'&&live.length>40?live:AI.anonKey;}
  async function callEngine(fields,l){const d=new Date(),response=await fetch(AI.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${authToken()}`,'apikey':AI.anonKey},body:JSON.stringify({mode,language:l,fields,client_local_date:localDate(),client_local_datetime:localDateTime(),client_timezone_offset_minutes:-d.getTimezoneOffset(),client_timezone_name:timezoneName(),device_id:deviceId(),client_elapsed_ms:Date.now()-pageOpenedAt,website:clean(trap.value)})});let data={};try{data=await response.json();}catch{}if(!response.ok){const err=new Error(data.error||`GUANSHI AI HTTP ${response.status}`);err.code=data.error_code||'';err.detail=data;throw err;}if(!data.result)throw new Error('No consultation result was returned.');return data;}
  function validationLink(){let a=output?.querySelector('[data-validation-link]');if(!a&&copyBtn){a=document.createElement('a');a.href='guanshi-validation.html';a.className='consult-btn secondary';a.dataset.validationLink='';copyBtn.parentElement?.appendChild(a);}return a;}
  function applyV16Labels(){const l=lang(),t=i18n[l]||i18n.en;document.querySelectorAll('[data-summary-label-en]').forEach(el=>el.dataset.summaryLabel=el.dataset[`summaryLabel${cap(l)}`]||el.dataset.summaryLabelEn);document.querySelectorAll('[data-current-label-en]').forEach(el=>el.dataset.currentLabel=el.dataset[`currentLabel${cap(l)}`]||el.dataset.currentLabelEn);if(copyBtn)copyBtn.textContent=t.copy;if(submitBtn)submitBtn.textContent=mode==='traditional'?t.submitTraditional:t.submitGeneral;if(outputTitle)outputTitle.textContent=mode==='traditional'?t.outputTraditional:t.outputGeneral;if(privacyNote){privacyNote.textContent=t.privacy;}const va=output?.querySelector('[data-validation-link]');if(va)va.textContent=t.validate;document.querySelectorAll('.consult-kicker').forEach(el=>{if(el.textContent.includes('RUNLU GUANSHI'))el.textContent='RUNLU GUANSHI · V1.6';});const fv=document.querySelector('.gs-footer > div');if(fv?.textContent.includes('RUNLU GUANSHI'))fv.textContent='RUNLU GUANSHI · V1.6';syncMethodPanels();}

  form.addEventListener('submit',async e=>{
    e.preventDefault(); syncMethodPanels(); if(!form.reportValidity())return; applyV16Labels();
    const data=new FormData(form),l=lang(),t=i18n[l]||i18n.en,fields=payloadFields(data),body=mode==='traditional'?buildTraditional(data):buildGeneral(data),title=mode==='traditional'?t.titleTraditional:t.titleGeneral,route=mode==='traditional'?t.routeTraditional:t.routeGeneral,note=mode==='traditional'?t.noteTraditional:t.noteGeneral,timestamp=new Date().toLocaleString(l==='zh'?'zh-CN':l),intro=[title,'',`${t.generated}: ${timestamp}`,`${t.route}: ${route}`,'',`【${t.input}】`,...body,''];
    output.classList.add('is-visible');pre.textContent=[...intro,t.thinking].join('\n');output.scrollIntoView({behavior:'smooth',block:'nearest'});output?.querySelector('[data-validation-link]')?.remove();if(submitBtn)submitBtn.disabled=true;
    try{
      const result=await callEngine(fields,l),quota=Number.isFinite(Number(result?.limits?.remaining_today))?t.quota(Number(result.limits.remaining_today)):'',fixed=[chartText(result.chart,t),structureText(result.traditional_structure,t)].filter(Boolean),full=[...intro,...fixed,`【${t.result}】`,result.result,'',quota,`${t.note}: ${note}`].filter(Boolean).join('\n');
      pre.textContent=full;sessionStorage.setItem(LAST_KEY,JSON.stringify({mode,generated_at:new Date().toISOString(),language:l,question:fields.question||'',fields,traditional_structure:result.traditional_structure||null,chart:result.chart||null,full_text:full}));const a=validationLink();if(a)a.textContent=t.validate;
    }catch(error){const code=error?.code||'',friendly=t.limits?.[code]||error?.message||'Request failed.';pre.textContent=[...intro,`⚠ ${friendly}`,'',`${t.note}: ${note}`].join('\n');}
    finally{if(submitBtn)submitBtn.disabled=false;}
  });
  copyBtn?.addEventListener('click',async()=>{const text=pre.textContent,l=lang(),t=i18n[l]||i18n.en;try{await navigator.clipboard.writeText(text);}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;opacity:0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}const old=copyBtn.textContent;copyBtn.textContent=t.copied;setTimeout(()=>copyBtn.textContent=old,1400);});
  form.addEventListener('reset',()=>{setTimeout(()=>{output?.classList.remove('is-visible');if(pre)pre.textContent='';trap.value='';output?.querySelector('[data-validation-link]')?.remove();sessionStorage.removeItem(LAST_KEY);syncMethodPanels();},0);});
  form.elements.method?.addEventListener('change',syncMethodPanels);
  document.querySelector('[data-runlu-language-select]')?.addEventListener('change',()=>setTimeout(applyV16Labels,0));
  applyV16Labels();
})();