(()=>{
'use strict';
const SUPABASE_URL='https://ekrnknlawekeoszzkamd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Jr12gnQ7UrU6Wv9xz4L1aA_bcTZiGqn';
const BUCKET='runlu-master-vault';
const MAX_BYTES=50*1024*1024;
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const els={authSection:$('authSection'),privateZone:$('privateZone'),authEmail:$('authEmail'),authPassword:$('authPassword'),signInBtn:$('signInBtn'),signUpBtn:$('signUpBtn'),signOutBtn:$('signOutBtn'),authMessage:$('authMessage'),accountEmail:$('accountEmail'),assetSelect:$('assetSelect'),fileRole:$('fileRole'),versionLabel:$('versionLabel'),releaseDate:$('releaseDate'),vaultFile:$('vaultFile'),vaultNotes:$('vaultNotes'),uploadBtn:$('uploadBtn'),clearBtn:$('clearBtn'),uploadMessage:$('uploadMessage'),exportBtn:$('exportBtn'),searchInput:$('searchInput'),assetFilter:$('assetFilter'),roleFilter:$('roleFilter'),vaultRows:$('vaultRows'),emptyState:$('emptyState'),statFiles:$('statFiles'),statAssets:$('statAssets'),statVerified:$('statVerified'),statSize:$('statSize')};
let currentUser=null,assets=[],records=[];
const I18N={
 en:{choose:'Choose an asset',all:'All assets',required:'Choose an asset and a file.',tooLarge:'File exceeds the 50 MB vault limit.',hashing:'Calculating SHA-256…',uploading:'Uploading private master copy…',recording:'Recording integrity metadata…',saved:'Master copy stored and recorded.',uploadFail:'Upload failed.',metaFail:'File upload succeeded but metadata recording failed; the uploaded object was removed when possible.',loadFail:'Could not load the vault.',verify:'Verify',download:'Download',remove:'Delete',verified:'Verified',notVerified:'Not verified',checking:'Checking file integrity…',match:'Integrity verified. SHA-256 matches.',mismatch:'Integrity check failed. SHA-256 does not match the recorded hash.',downloadFail:'Download failed.',deleteAsk:'Permanently delete this master copy and its vault record?',deleteFail:'Delete failed.',deleted:'Master copy deleted.',accountCreated:'Account created. If email confirmation is enabled, confirm the email before signing in.',signedIn:'Signed in.',signedOut:'Signed out.',exported:'Manifest exported.'},
 zh:{choose:'选择一项资产',all:'全部资产',required:'请选择对应资产和文件。',tooLarge:'文件超过母版库 50 MB 上限。',hashing:'正在计算 SHA-256…',uploading:'正在上传私人母版…',recording:'正在登记完整性元数据…',saved:'母版已存入并完成登记。',uploadFail:'上传失败。',metaFail:'文件已上传，但元数据登记失败；系统已尽可能移除刚上传的文件。',loadFail:'母版资产库加载失败。',verify:'校验',download:'下载',remove:'删除',verified:'已校验',notVerified:'未校验',checking:'正在校验文件完整性…',match:'完整性校验通过，SHA-256 一致。',mismatch:'完整性校验失败，SHA-256 与记录不一致。',downloadFail:'下载失败。',deleteAsk:'永久删除这份母版及其登记记录？',deleteFail:'删除失败。',deleted:'母版已删除。',accountCreated:'账户已创建。如果开启邮箱确认，请先确认邮件后再登录。',signedIn:'登录成功。',signedOut:'已退出登录。',exported:'清单已导出。'},
 fr:{choose:'Choisir un actif',all:'Tous les actifs',required:'Choisissez un actif et un fichier.',tooLarge:'Le fichier dépasse la limite de 50 Mo.',hashing:'Calcul du SHA-256…',uploading:'Téléversement du master privé…',recording:'Enregistrement des métadonnées…',saved:'Master stocké et enregistré.',uploadFail:'Échec du téléversement.',metaFail:'Le fichier a été téléversé mais les métadonnées ont échoué; suppression tentée.',loadFail:'Impossible de charger le coffre.',verify:'Vérifier',download:'Télécharger',remove:'Supprimer',verified:'Vérifié',notVerified:'Non vérifié',checking:'Vérification de l’intégrité…',match:'Intégrité vérifiée. SHA-256 identique.',mismatch:'Échec de l’intégrité. SHA-256 différent.',downloadFail:'Échec du téléchargement.',deleteAsk:'Supprimer définitivement ce master et sa fiche ?',deleteFail:'Échec de la suppression.',deleted:'Master supprimé.',accountCreated:'Compte créé. Confirmez l’e-mail si nécessaire.',signedIn:'Connecté.',signedOut:'Déconnecté.',exported:'Manifeste exporté.'},
 es:{choose:'Elegir un activo',all:'Todos los activos',required:'Elija un activo y un archivo.',tooLarge:'El archivo supera el límite de 50 MB.',hashing:'Calculando SHA-256…',uploading:'Subiendo máster privado…',recording:'Registrando metadatos…',saved:'Máster guardado y registrado.',uploadFail:'Error de carga.',metaFail:'El archivo se cargó pero falló el registro; se intentó eliminar el objeto.',loadFail:'No se pudo cargar la bóveda.',verify:'Verificar',download:'Descargar',remove:'Eliminar',verified:'Verificado',notVerified:'No verificado',checking:'Verificando integridad…',match:'Integridad verificada. SHA-256 coincide.',mismatch:'Falló la integridad. SHA-256 no coincide.',downloadFail:'Error de descarga.',deleteAsk:'¿Eliminar permanentemente este máster y su registro?',deleteFail:'Error al eliminar.',deleted:'Máster eliminado.',accountCreated:'Cuenta creada. Confirme el correo si es necesario.',signedIn:'Sesión iniciada.',signedOut:'Sesión cerrada.',exported:'Manifiesto exportado.'}
};
function lang(){return document.documentElement.dataset.runluLanguage||'en'}
function t(k){return I18N[lang()]?.[k]||I18N.en[k]||k}
function msg(el,text,error=false){el.textContent=text||'';el.style.color=error?'#9b3f32':'#47644f'}
function busy(btn,on){btn.disabled=on}
function bytes(n){n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`}
function safeName(name){const parts=String(name||'file').split('.');const ext=parts.length>1?'.'+parts.pop().replace(/[^A-Za-z0-9]/g,'').slice(0,10):'';let base=parts.join('.').normalize('NFKD').replace(/[^A-Za-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);if(!base)base='master';return base+ext}
function safeKey(k){return String(k||'asset').toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'asset'}
async function sha256(blob){const buf=await blob.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buf);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')}
function assetName(key){return assets.find(a=>a.asset_key===key)?.name||records.find(r=>r.asset_key===key)?.display_name||key}
function roleLabel(role){const map={master:'Master',source:'Source package',release:'Release package',publication:'Publication file',cover:'Cover / artwork',metadata:'Metadata',snapshot:'Stable snapshot',backup:'Backup copy',other:'Other'};return map[role]||role}
async function signIn(){const email=els.authEmail.value.trim(),password=els.authPassword.value;if(!email||!password)return msg(els.authMessage,'Email and password are required.',true);busy(els.signInBtn,true);const {error}=await db.auth.signInWithPassword({email,password});busy(els.signInBtn,false);if(error)return msg(els.authMessage,error.message,true);msg(els.authMessage,t('signedIn'))}
async function signUp(){const email=els.authEmail.value.trim(),password=els.authPassword.value;if(!email||password.length<8)return msg(els.authMessage,'Use a valid email and a password of at least 8 characters.',true);busy(els.signUpBtn,true);const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:'https://runlu.ca/master-vault.html'}});busy(els.signUpBtn,false);if(error)return msg(els.authMessage,error.message,true);msg(els.authMessage,data.session?t('signedIn'):t('accountCreated'))}
async function signOut(){await db.auth.signOut();msg(els.authMessage,t('signedOut'))}
async function loadAssets(){if(!currentUser)return;const {data,error}=await db.from('runlu_asset_ledger').select('asset_key,name').eq('user_id',currentUser.id).order('name');assets=error?[]:(data||[]);refreshAssetOptions()}
function refreshAssetOptions(){const selected=els.assetSelect.value,filter=els.assetFilter.value;els.assetSelect.innerHTML='';els.assetFilter.innerHTML='';const choose=document.createElement('option');choose.value='';choose.textContent=t('choose');els.assetSelect.appendChild(choose);const all=document.createElement('option');all.value='';all.textContent=t('all');els.assetFilter.appendChild(all);const map=new Map();assets.forEach(a=>map.set(a.asset_key,a.name));records.forEach(r=>{if(!map.has(r.asset_key))map.set(r.asset_key,r.display_name)});[...map.entries()].sort((a,b)=>a[1].localeCompare(b[1])).forEach(([key,name])=>{const a=document.createElement('option');a.value=key;a.textContent=name;els.assetSelect.appendChild(a);const f=a.cloneNode(true);els.assetFilter.appendChild(f)});if([...map.keys()].includes(selected))els.assetSelect.value=selected;if([...map.keys()].includes(filter))els.assetFilter.value=filter}
async function loadRecords(){if(!currentUser)return;const {data,error}=await db.from('runlu_master_vault').select('*').eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error){msg(els.uploadMessage,t('loadFail')+' '+error.message,true);return}records=data||[];refreshAssetOptions();render()}
function filtered(){const q=els.searchInput.value.trim().toLowerCase(),ak=els.assetFilter.value,role=els.roleFilter.value;return records.filter(r=>{const hay=[r.display_name,r.original_filename,r.asset_key,r.file_role,r.version_label,r.notes,r.sha256].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!ak||r.asset_key===ak)&&(!role||r.file_role===role)})}
function render(){const rows=filtered();els.vaultRows.innerHTML='';rows.forEach(r=>{const tr=document.createElement('tr');const tdFile=document.createElement('td');const strong=document.createElement('strong');strong.textContent=assetName(r.asset_key);const br=document.createElement('br');const small=document.createElement('span');small.className='muted';small.textContent=r.original_filename;tdFile.append(strong,br,small);const tdRole=document.createElement('td');tdRole.textContent=roleLabel(r.file_role);const tdVer=document.createElement('td');tdVer.textContent=r.version_label||'—';const tdSize=document.createElement('td');tdSize.textContent=bytes(r.size_bytes);const tdHash=document.createElement('td');const code=document.createElement('span');code.className='hash';code.title=r.sha256||'';code.textContent=r.sha256?r.sha256.slice(0,14)+'…':'—';tdHash.appendChild(code);const tdInt=document.createElement('td');const pill=document.createElement('span');pill.className='pill '+(r.verified_at?'ok':'muted');pill.textContent=r.verified_at?t('verified'):t('notVerified');tdInt.appendChild(pill);const tdDate=document.createElement('td');tdDate.textContent=(r.created_at||'').slice(0,10);const tdAct=document.createElement('td');const acts=document.createElement('div');acts.className='row-actions';[['download',t('download')],['verify',t('verify')],['delete',t('remove')]].forEach(([kind,label])=>{const b=document.createElement('button');b.type='button';b.className='row-link'+(kind==='delete'?' danger':'');b.textContent=label;b.addEventListener('click',()=>kind==='download'?downloadRecord(r):kind==='verify'?verifyRecord(r):deleteRecord(r));acts.appendChild(b)});tdAct.appendChild(acts);tr.append(tdFile,tdRole,tdVer,tdSize,tdHash,tdInt,tdDate,tdAct);els.vaultRows.appendChild(tr)});els.emptyState.classList.toggle('hidden',rows.length>0);els.statFiles.textContent=records.length;els.statAssets.textContent=new Set(records.map(r=>r.asset_key)).size;els.statVerified.textContent=records.filter(r=>r.verified_at).length;els.statSize.textContent=bytes(records.reduce((s,r)=>s+Number(r.size_bytes||0),0))}
function clearForm(){els.assetSelect.value='';els.fileRole.value='master';els.versionLabel.value='';els.releaseDate.value='';els.vaultFile.value='';els.vaultNotes.value='';msg(els.uploadMessage,'')}
async function uploadMaster(){if(!currentUser)return;const key=els.assetSelect.value,file=els.vaultFile.files[0];if(!key||!file)return msg(els.uploadMessage,t('required'),true);if(file.size>MAX_BYTES)return msg(els.uploadMessage,t('tooLarge'),true);busy(els.uploadBtn,true);let hash='';try{msg(els.uploadMessage,t('hashing'));hash=await sha256(file);msg(els.uploadMessage,t('uploading'));const stamp=new Date().toISOString().replace(/[:.]/g,'-');const path=`${currentUser.id}/${safeKey(key)}/${stamp}-${safeName(file.name)}`;const {error:upErr}=await db.storage.from(BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false,cacheControl:'3600'});if(upErr)throw new Error(t('uploadFail')+' '+upErr.message);msg(els.uploadMessage,t('recording'));const payload={user_id:currentUser.id,asset_key:key,display_name:assetName(key),file_role:els.fileRole.value,version_label:els.versionLabel.value.trim()||null,storage_path:path,original_filename:file.name,mime_type:file.type||null,size_bytes:file.size,sha256:hash,release_date:els.releaseDate.value||null,notes:els.vaultNotes.value.trim()||null};const {error:metaErr}=await db.from('runlu_master_vault').insert(payload);if(metaErr){await db.storage.from(BUCKET).remove([path]).catch(()=>{});throw new Error(t('metaFail')+' '+metaErr.message)}msg(els.uploadMessage,t('saved'));clearForm();msg(els.uploadMessage,t('saved'));await loadRecords()}catch(e){msg(els.uploadMessage,e.message||String(e),true)}finally{busy(els.uploadBtn,false)}}
async function getBlob(r){const {data,error}=await db.storage.from(BUCKET).download(r.storage_path);if(error)throw new Error(t('downloadFail')+' '+error.message);return data}
async function downloadRecord(r){try{msg(els.uploadMessage,'');const blob=await getBlob(r);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=r.original_filename||'master-copy';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){msg(els.uploadMessage,e.message,true)}}
async function verifyRecord(r){try{msg(els.uploadMessage,t('checking'));const blob=await getBlob(r);const h=await sha256(blob);if(!r.sha256||h!==r.sha256)return msg(els.uploadMessage,t('mismatch'),true);const now=new Date().toISOString();const {error}=await db.from('runlu_master_vault').update({verified_at:now,updated_at:now}).eq('id',r.id).eq('user_id',currentUser.id);if(error)throw error;msg(els.uploadMessage,t('match'));await loadRecords()}catch(e){msg(els.uploadMessage,e.message||String(e),true)}}
async function deleteRecord(r){if(!confirm(t('deleteAsk')))return;try{const {error:storeErr}=await db.storage.from(BUCKET).remove([r.storage_path]);if(storeErr)throw storeErr;const {error:rowErr}=await db.from('runlu_master_vault').delete().eq('id',r.id).eq('user_id',currentUser.id);if(rowErr)throw rowErr;msg(els.uploadMessage,t('deleted'));await loadRecords()}catch(e){msg(els.uploadMessage,t('deleteFail')+' '+(e.message||e),true)}}
function exportManifest(){const manifest={format:'RUNLU Master Copy Vault Manifest',version:1,exported_at:new Date().toISOString(),account:currentUser?.email||null,records:records.map(({user_id,...r})=>r)};const blob=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`runlu-master-vault-manifest-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);msg(els.uploadMessage,t('exported'))}
async function applySession(session){currentUser=session?.user||null;els.authSection.classList.toggle('hidden',!!currentUser);els.privateZone.classList.toggle('hidden',!currentUser);if(!currentUser){assets=[];records=[];return}els.accountEmail.textContent=currentUser.email||currentUser.id;await loadAssets();await loadRecords()}
els.signInBtn.addEventListener('click',signIn);els.signUpBtn.addEventListener('click',signUp);els.signOutBtn.addEventListener('click',signOut);els.uploadBtn.addEventListener('click',uploadMaster);els.clearBtn.addEventListener('click',clearForm);els.exportBtn.addEventListener('click',exportManifest);els.searchInput.addEventListener('input',render);els.assetFilter.addEventListener('change',render);els.roleFilter.addEventListener('change',render);window.addEventListener('runlu:languagechange',()=>{refreshAssetOptions();render()});
db.auth.getSession().then(({data})=>applySession(data.session));db.auth.onAuthStateChange((_event,session)=>setTimeout(()=>applySession(session),0));
})();
