/* RUNLU Flooring OS Universal · U1 Supplier PO foundation
   Quote-ready Job → Supplier PO. Local prototype; digital numbering is NOT multi-user safe yet. */
(function(){
'use strict';
const PO='runlu_flooring_universal_u1_supplier_orders', SETTINGS='runlu_flooring_universal_u1_po_settings', WS='runlu_flooring_universal_u0_workspace';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch(_){return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const w=()=>read(WS,null),org=()=>w()?.company?.organizationId||'',loc=()=>w()?.location?.locationId||'', all=()=>read(PO,[]), pos=()=>all().filter(x=>x.organizationId===org());
function save(xs){write(PO,[...all().filter(x=>x.organizationId!==org()),...xs])}
function uid(){return 'po-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function createFromJob(jobId){const job=window.RUNLUUniversalSales?.jobs().find(x=>x.id===jobId);if(!job)return alert('Job not found.');if(job.quoteStatus!=='Ready')return alert('Mark the Quote Ready before creating a Supplier PO.');const supplier=prompt('Supplier name');if(!supplier)return;const xs=pos();xs.unshift({id:uid(),organizationId:org(),locationId:loc(),jobId:job.id,jobNumber:job.jobNumber||'',customerName:job.customerName||'',salesRep:job.salesRep||'',supplier:supplier.trim(),mode:'digital',poNumber:'',status:'Draft',items:JSON.parse(JSON.stringify(job.items||[])),createdAt:new Date().toISOString()});save(xs);render()}
function recordManual(id){const xs=pos(),p=xs.find(x=>x.id===id);if(!p)return;const n=prompt('Existing paper PO number');if(!n)return;if(xs.some(x=>x.id!==id&&String(x.poNumber)===n))return alert('That PO number already exists in this company.');p.mode='manual';p.poNumber=n.trim();p.status='Issued';p.issuedAt=new Date().toISOString();save(xs);render()}
function render(){const host=document.getElementById('universalPO');if(!host)return;const jobs=(window.RUNLUUniversalSales?.jobs()||[]).filter(j=>j.quoteStatus==='Ready'),xs=pos();host.innerHTML='<div class="card"><h2>PO / Supplier Orders</h2><p class="muted">Quote Ready → Supplier PO. One Job may have multiple supplier POs.</p><div class="uPOJobs">'+(jobs.length?jobs.map(j=>'<button data-po-job="'+esc(j.id)+'">'+esc(j.customerName)+' · #'+esc(j.jobNumber||'—')+' → New PO</button>').join(''):'<span class="muted">No Quote Ready jobs yet.</span>')+'</div></div><div class="card"><h3>Supplier Order Ledger</h3>'+(xs.length?xs.map(p=>'<div class="uPORow"><div><b>'+(p.poNumber?'#'+esc(p.poNumber):'Draft')+' · '+esc(p.supplier)+'</b><span>'+esc(p.customerName)+' · '+esc(p.status)+' · '+esc(p.mode)+'</span></div>'+(p.poNumber?'':'<button data-manual="'+esc(p.id)+'">Record Manual PO</button>')+'</div>').join(''):'<p class="muted">No supplier orders yet.</p>')+'<p class="muted"><b>Digital numbering:</b> reserved for the central transactional backend. Local U1 will not issue automatic numbers.</p></div>';host.querySelectorAll('[data-po-job]').forEach(b=>b.onclick=()=>createFromJob(b.dataset.poJob));host.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>recordManual(b.dataset.manual))}
window.RUNLUUniversalPO=Object.freeze({render,pos});
})();