/* RUNLU Flooring OS Universal · U1 Sales / Jobs
   Customer → Job → Items → Estimate / Quote. Tenant-owned from creation. */
(function(){
'use strict';
const JOB_STORE='runlu_flooring_universal_u1_jobs', TEAM_STORE='runlu_flooring_universal_u1_sales_team', WORKSPACE_STORE='runlu_flooring_universal_u0_workspace';
const $=id=>document.getElementById(id), read=(k,d)=>window.RUNLUUniversalData.read(k,d), write=(k,v)=>window.RUNLUUniversalData.write(k,v);
const workspace=()=>read(WORKSPACE_STORE,null), tenant=()=>workspace()?.company?.organizationId||'', locationId=()=>workspace()?.location?.locationId||'';
const jobs=()=>read(JOB_STORE,[]).filter(j=>j.organizationId===tenant()), team=()=>read(TEAM_STORE,[]).filter(r=>r.organizationId===tenant());
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), num=v=>Number.isFinite(Number(v))?Number(v):0;
const money=v=>new Intl.NumberFormat(workspace()?.company?.locale||'en-CA',{style:'currency',currency:workspace()?.company?.currency||'CAD'}).format(num(v));
function saveJobs(xs){const all=read(JOB_STORE,[]).filter(j=>j.organizationId!==tenant());write(JOB_STORE,[...all,...xs])}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function totals(j){const subtotal=(j.items||[]).reduce((s,x)=>s+num(x.qty)*num(x.unitPrice),0),discount=num(j.discount),net=Math.max(0,subtotal-discount),taxRate=num(j.taxRate),tax=Math.round(net*taxRate*100)/100;return{subtotal,discount,net,tax,total:net+tax}}
function render(){
 const w=workspace(),host=$('universalSales');if(!host)return;if(!w){host.innerHTML='<p>Create a company workspace first.</p>';return}
 const xs=jobs().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
 host.innerHTML='<div class="card"><h2>Sales / Jobs</h2><p class="muted">Customer → Job → Items → Estimate / Quote · '+esc(w.company.displayName||w.company.legalName)+'</p><div class="grid"><label>Customer<input id="uSalesCustomer" list="uSalesCustomerList" placeholder="Customer name"><datalist id="uSalesCustomerList">'+(window.RUNLUUniversalCustomers?.rows?.()||[]).map(c=>'<option value="'+esc(c.name)+'">').join('')+'</datalist></label><label>Phone / Email<input id="uSalesContact" placeholder="Contact"></label><label>Job / Order #<input id="uSalesNumber" placeholder="Optional"></label><label>Sales Rep<input id="uSalesRep" list="uSalesRepList" placeholder="Salesperson"><datalist id="uSalesRepList">'+team().map(r=>'<option value="'+esc(r.name)+'">').join('')+'</datalist></label></div><p><button class="primary" id="uSalesAdd">Create Job / Order</button></p></div><div class="card"><h3>Jobs / Orders</h3>'+(xs.length?xs.map(jobCard).join(''):'<p class="muted">No jobs yet for this company.</p>')+'</div>';
 $('uSalesAdd')?.addEventListener('click',()=>{const customer=$('uSalesCustomer').value.trim();if(!customer)return alert('Enter a customer name.');const contact=$('uSalesContact').value.trim(),a=jobs(),existing=window.RUNLUUniversalCustomers?.resolve?.(customer,contact);const j={id:uid('job'),organizationId:tenant(),locationId:locationId(),customerId:existing?.id||'',customerName:customer,customerContact:contact,jobNumber:$('uSalesNumber').value.trim(),salesRep:$('uSalesRep').value.trim(),status:'Draft',quoteStatus:'Working',taxRate:0,discount:0,items:[],createdAt:new Date().toISOString()};a.push(j);saveJobs(a);const master=window.RUNLUUniversalCustomers?.upsertFromJob?.(j);if(master&&!j.customerId){j.customerId=master.id;saveJobs(a)}render()});
 host.querySelectorAll('[data-add-item]').forEach(b=>b.addEventListener('click',()=>addItem(b.dataset.addItem)));
 host.querySelectorAll('[data-quote]').forEach(b=>b.addEventListener('click',()=>setQuote(b.dataset.quote)));
 host.querySelectorAll('[data-order]').forEach(b=>b.addEventListener('click',()=>confirmOrder(b.dataset.order)));
 host.querySelectorAll('[data-status]').forEach(s=>s.addEventListener('change',()=>setStatus(s.dataset.status,s.value)));
}
function jobCard(j){const t=totals(j);return '<div class="uJobCard" data-record-id="'+esc(j.id)+'" data-record-status="'+esc(j.status)+'" data-quote-status="'+esc(j.quoteStatus||"Working")+'"><div class="uJobHead"><div><b>'+esc(j.customerName)+'</b><span>#'+esc(j.jobNumber||'—')+' · '+esc(j.salesRep||'Unassigned')+' · '+esc(j.customerContact||'No contact')+'</span></div><select data-status="'+esc(j.id)+'"><option'+(j.status==='Draft'?' selected':'')+'>Draft</option><option'+(j.status==='In Progress'?' selected':'')+'>In Progress</option><option'+(j.status==='Completed'?' selected':'')+'>Completed</option><option'+(j.status==='Archived'?' selected':'')+'>Archived</option></select></div><div class="uItems">'+((j.items||[]).length?(j.items||[]).map(x=>'<div><span>'+esc(x.description)+'</span><span>'+esc(x.qty)+' × '+money(x.unitPrice)+'</span></div>').join(''):'<span class="muted">No items yet.</span>')+'</div><div class="uAddItem"><input id="desc-'+j.id+'" placeholder="Material / service"><input id="qty-'+j.id+'" type="number" min="0" step="0.01" placeholder="Qty"><input id="price-'+j.id+'" type="number" min="0" step="0.01" placeholder="Unit price"><button class="primary" data-add-item="'+j.id+'">Add Item</button></div><div class="uQuote"><span>Estimate: <b>'+money(t.total)+'</b></span><span>Quote: <b>'+esc(j.quoteStatus||'Working')+'</b></span><span>Order: <b>'+esc(j.orderStatus||'Not Confirmed')+'</b></span>'+(j.quoteStatus!=='Ready'?'<button data-quote="'+j.id+'">Mark Quote Ready</button>':j.orderStatus!=='Confirmed'?'<button class="primary" data-order="'+j.id+'">Confirm Order</button>':'<strong>ORDER CONFIRMED</strong>')+'</div></div>'}
function addItem(jobId){const xs=jobs(),j=xs.find(x=>x.id===jobId);if(!j)return;const d=$('desc-'+jobId)?.value.trim(),q=num($('qty-'+jobId)?.value),p=num($('price-'+jobId)?.value);if(!d||q<=0)return alert('Enter an item and quantity.');j.items=j.items||[];j.items.push({id:uid('item'),description:d,qty:q,unitPrice:p});j.status=j.status==='Draft'?'In Progress':j.status;saveJobs(xs);render()}
function setQuote(jobId){const xs=jobs(),j=xs.find(x=>x.id===jobId);if(!j)return;j.quoteStatus='Ready';j.quoteReadyAt=new Date().toISOString();saveJobs(xs);render()}
function confirmOrder(jobId){const xs=jobs(),j=xs.find(x=>x.id===jobId);if(!j||j.quoteStatus!=='Ready')return;if(!(j.items||[]).length)return alert('Add at least one material or service item before confirming the order.');const tx=window.RUNLUUniversalCrashJournal?.begin?.('Sales Job','confirm-order',{jobId:j.id});const prev=j.status;j.orderStatus='Confirmed';j.orderConfirmedAt=new Date().toISOString();j.status='In Progress';window.RUNLUUniversalAudit?.log('Sales Job',j.id,'confirm-order',prev,j.status,{jobNumber:j.jobNumber||'',customerName:j.customerName});if(tx)window.RUNLUUniversalCrashJournal.phase(tx.id,'AUDIT_SAVED');saveJobs(xs);if(tx){window.RUNLUUniversalCrashJournal.phase(tx.id,'BUSINESS_SAVED');window.RUNLUUniversalCrashJournal.commit(tx.id)}render()}
function setStatus(jobId,status){const xs=jobs(),j=xs.find(x=>x.id===jobId);if(!j)return;j.status=status;saveJobs(xs)}
function closePaidJob(jobId,meta={}){const xs=jobs(),j=xs.find(x=>x.id===jobId);if(!j)return false;if(j.status==='Completed'&&j.financialStatus==='Paid')return true;const prev=j.status;j.financialStatus='Paid';j.status='Completed';j.completedAt=j.completedAt||new Date().toISOString();j.closedAt=new Date().toISOString();window.RUNLUUniversalAudit?.log('Sales Job',j.id,'financial-close',prev,j.status,{jobNumber:j.jobNumber||'',customerName:j.customerName,invoiceId:meta.invoiceId||'',invoiceNumber:meta.invoiceNumber||''});saveJobs(xs);return true}
window.RUNLUUniversalSales=Object.freeze({render,jobs,totals,confirmOrder,closePaidJob});
})();