/* RUNLU Flooring OS Universal · U1 inbound material flow
   Supplier PO → Pickup / Delivery → Receiving → Warehouse Ready. Local prototype. */
(function(){
'use strict';
const STORE='runlu_flooring_universal_u1_inbound_tasks',WS='runlu_flooring_universal_u0_workspace';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch(_){return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const w=()=>read(WS,null),org=()=>w()?.company?.organizationId||'',all=()=>read(STORE,[]),tasks=()=>all().filter(x=>x.organizationId===org());
function save(xs){write(STORE,[...all().filter(x=>x.organizationId!==org()),...xs])}
function uid(){return 'in-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function syncPOs(){const xs=tasks(),ids=new Set(xs.map(x=>x.poId));(window.RUNLUUniversalPO?.pos()||[]).filter(p=>p.status!=='Cancelled').forEach(p=>{if(!ids.has(p.id))xs.push({id:uid(),organizationId:p.organizationId,locationId:p.locationId,poId:p.id,poNumber:p.poNumber||'',jobId:p.jobId,jobNumber:p.jobNumber,customerName:p.customerName,supplier:p.supplier,items:JSON.parse(JSON.stringify(p.items||[])),fulfillment:'Pickup',purchaseType:'Job-specific',requestedDate:'',status:'Scheduled',receivedItems:[],warehouseNotes:'',createdAt:new Date().toISOString()})});save(xs);return xs}
function patch(id,fn){const xs=tasks(),x=xs.find(t=>t.id===id);if(!x)return;fn(x);x.updatedAt=new Date().toISOString();save(xs);render()}
function render(){const host=document.getElementById('universalInbound');if(!host)return;const xs=syncPOs().sort((a,b)=>String(a.requestedDate||'9999').localeCompare(String(b.requestedDate||'9999')));host.innerHTML='<div class="card"><h2>Pickup / Receiving</h2><p class="muted">Supplier PO → Pickup / Supplier Delivery → Receiving → Warehouse Ready.</p></div><div class="card">'+(xs.length?xs.map(t=>'<div class="uInbound"><div><b>'+(t.poNumber?'#'+esc(t.poNumber):'PO Draft')+' · '+esc(t.supplier)+'</b><span>'+esc(t.customerName||'Stock')+' · '+esc(t.status)+'</span></div><select data-fulfill="'+t.id+'"><option'+(t.fulfillment==='Pickup'?' selected':'')+'>Pickup</option><option'+(t.fulfillment==='Supplier Delivery'?' selected':'')+'>Supplier Delivery</option></select><input type="date" data-date="'+t.id+'" value="'+esc(t.requestedDate||'')+'"><select data-state="'+t.id+'">'+['Scheduled','In Progress','Picked Up','Received','Ready','Delayed','Completed','Cancelled'].map(s=>'<option'+(s===t.status?' selected':'')+'>'+s+'</option>').join('')+'</select><button data-receive="'+t.id+'">Receive Items</button></div>').join(''):'<p class="muted">No supplier POs to receive.</p>')+'</div>';
 host.querySelectorAll('[data-fulfill]').forEach(e=>e.onchange=()=>patch(e.dataset.fulfill,x=>x.fulfillment=e.value));host.querySelectorAll('[data-date]').forEach(e=>e.onchange=()=>patch(e.dataset.date,x=>x.requestedDate=e.value));host.querySelectorAll('[data-state]').forEach(e=>e.onchange=()=>patch(e.dataset.state,x=>x.status=e.value));host.querySelectorAll('[data-receive]').forEach(e=>e.onclick=()=>patch(e.dataset.receive,x=>{x.receivedItems=(x.items||[]).map(i=>({...i,receivedQty:i.qty}));x.receivedAt=new Date().toISOString();x.status='Ready'}) );
}
window.RUNLUUniversalInbound=Object.freeze({render,tasks});
})();