/* RUNLU Flooring OS Universal · U1 Customer Invoice + Payment
   Installation Completed → Customer Invoice → Payment → Job Completed. */
(function(){
'use strict';
const STORE='runlu_flooring_universal_u1_customer_invoices',WS='runlu_flooring_universal_u0_workspace';
const read=(k,d)=>window.RUNLUUniversalData.read(k,d),write=(k,v)=>window.RUNLUUniversalData.write(k,v),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),num=v=>Number.isFinite(Number(v))?Number(v):0;
const workspace=()=>read(WS,null),org=()=>workspace()?.company?.organizationId||'',all=()=>read(STORE,[]),rows=()=>all().filter(x=>x.organizationId===org());
function save(xs){write(STORE,[...all().filter(x=>x.organizationId!==org()),...xs])}
function salesJob(id){return (window.RUNLUUniversalSales?.jobs()||[]).find(x=>x.id===id)}
function totals(j){return window.RUNLUUniversalSales?.totals(j)||{subtotal:0,discount:0,net:0,tax:0,total:0}}
function sync(){const xs=rows(),jobs=new Set(xs.map(x=>x.jobId));(window.RUNLUUniversalInstallation?.rows()||[]).filter(i=>i.status==='Completed').forEach(i=>{if(jobs.has(i.jobId))return;const j=salesJob(i.jobId);if(!j)return;const t=totals(j);xs.unshift({id:'inv-'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),organizationId:j.organizationId,locationId:j.locationId,jobId:j.id,jobNumber:j.jobNumber||'',customerName:j.customerName||'',invoiceNumber:'',subtotal:t.subtotal||0,discount:t.discount||0,tax:t.tax||0,total:t.total||0,paidAmount:0,balance:t.total||0,status:'Draft',payments:[],createdAt:new Date().toISOString()});jobs.add(i.jobId)});save(xs);return xs}
function issue(id){const xs=rows(),r=xs.find(x=>x.id===id);if(!r)return;const n=prompt('Customer invoice number');if(!n)return;if(xs.some(x=>x.id!==id&&x.invoiceNumber===n.trim()))return alert('That invoice number already exists in this company.');if(!window.RUNLUUniversalGuards?.assert('invoice',r.status,'Issued'))return;const invoiceNumber=n.trim(),tx=window.RUNLUUniversalCrashJournal?.begin?.('Customer Invoice','issue',{invoiceId:r.id,jobId:r.jobId});const prev=r.status;r.invoiceNumber=invoiceNumber;r.status='Issued';window.RUNLUUniversalAudit?.log('Customer Invoice',r.id,'status',prev,r.status,{invoiceNumber:r.invoiceNumber,jobId:r.jobId});r.issuedAt=new Date().toISOString();save(xs);if(tx)window.RUNLUUniversalCrashJournal.commit(tx.id);render()}
function pay(id){const xs=rows(),r=xs.find(x=>x.id===id);if(!r||!r.invoiceNumber)return;const raw=prompt('Payment amount',String(r.balance));if(raw===null)return;const amount=Math.max(0,num(raw));if(!amount)return;const method=prompt('Payment method','Card')||'Other',paymentId='pay-'+Date.now().toString(36);const tx=window.RUNLUUniversalCrashJournal?.begin?.('Customer Payment','record',{invoiceId:r.id,jobId:r.jobId,paymentId,amount});r.payments.push({id:paymentId,amount,method,createdAt:new Date().toISOString()});window.RUNLUUniversalAudit?.log('Customer Payment',r.id,'record',r.status,'Payment Recorded',{invoiceNumber:r.invoiceNumber,amount,method,jobId:r.jobId});r.paidAmount=r.payments.reduce((s,p)=>s+num(p.amount),0);r.balance=Math.max(0,num(r.total)-r.paidAmount);const next=r.balance<=0?'Paid':'Partially Paid';if(!window.RUNLUUniversalGuards?.assert('invoice',r.status,next)){if(tx)window.RUNLUUniversalCrashJournal.abort(tx.id,'Lifecycle guard rejected payment state');return;}r.status=next;if(r.status==='Paid')r.paidAt=new Date().toISOString();save(xs);if(tx)window.RUNLUUniversalCrashJournal.commit(tx.id);render()}
function render(){const host=document.getElementById('universalCustomerBilling');if(!host)return;const xs=sync(),cfg=workspace()?.company||{},fmt=n=>new Intl.NumberFormat(cfg.locale||'en-CA',{style:'currency',currency:cfg.currency||'CAD'}).format(num(n));host.innerHTML='<div class="card"><h2>Customer Invoice / Payment</h2><p class="muted">Installation Completed → invoice → payment → financial completion.</p></div><div class="card">'+(xs.length?xs.map(r=>'<div class="uBill"><div class="uBillHead"><div><b>'+esc(r.customerName)+' · '+(r.invoiceNumber?'Invoice #'+esc(r.invoiceNumber):'Invoice Draft')+'</b><span>Job #'+esc(r.jobNumber||'—')+' · '+esc(r.status)+'</span></div><strong>'+fmt(r.balance)+' due</strong></div><div class="uBillTotals"><span>Total <b>'+fmt(r.total)+'</b></span><span>Paid <b>'+fmt(r.paidAmount)+'</b></span><span>Balance <b>'+fmt(r.balance)+'</b></span></div><div class="uBillActions">'+(!r.invoiceNumber?'<button data-issue="'+r.id+'">Issue Invoice</button>':'')+(r.invoiceNumber&&r.balance>0?'<button class="primary" data-pay="'+r.id+'">Record Payment</button>':'')+(r.status==='Paid'?'<strong>Job financially complete</strong>':'')+'</div></div>').join(''):'<p class="muted">No completed installations awaiting customer billing.</p>')+'</div>';host.querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>issue(b.dataset.issue));host.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>pay(b.dataset.pay))}
window.RUNLUUniversalBilling=Object.freeze({render,rows,issue,pay});
})();