/* RUNLU Flooring OS Universal · U1 inbound material flow
   Ordered → Received → Partial / Backorder / Damage → Warehouse Ready. Local prototype. */
(function(){
'use strict';
const STORE='runlu_flooring_universal_u1_inbound_tasks',WS='runlu_flooring_universal_u0_workspace';
const read=(k,d)=>window.RUNLUUniversalData.read(k,d),write=(k,v)=>window.RUNLUUniversalData.write(k,v),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),num=v=>Number.isFinite(Number(v))?Number(v):0;
const w=()=>read(WS,null),org=()=>w()?.company?.organizationId||'',all=()=>read(STORE,[]),tasks=()=>all().filter(x=>x.organizationId===org());
function save(xs){write(STORE,[...all().filter(x=>x.organizationId!==org()),...xs])}
function uid(){return 'in-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function syncPOs(){const xs=tasks(),ids=new Set(xs.map(x=>x.poId));(window.RUNLUUniversalPO?.pos()||[]).filter(p=>p.status!=='Cancelled').forEach(p=>{if(!ids.has(p.id))xs.push({id:uid(),organizationId:p.organizationId,locationId:p.locationId,poId:p.id,poNumber:p.poNumber||'',jobId:p.jobId,jobNumber:p.jobNumber,customerName:p.customerName,supplier:p.supplier,items:JSON.parse(JSON.stringify(p.items||[])),fulfillment:'Pickup',purchaseType:'Job-specific',requestedDate:'',status:'Scheduled',receivedItems:[],exceptions:[],createdAt:new Date().toISOString()})});save(xs);return xs}
function patch(id,fn){const xs=tasks(),x=xs.find(t=>t.id===id);if(!x)return;fn(x);x.updatedAt=new Date().toISOString();save(xs);if(tx)window.RUNLUUniversalCrashJournal.commit(tx.id);render()}
function receive(id){const xs=tasks(),t=xs.find(x=>x.id===id);if(!t)return;const tx=window.RUNLUUniversalCrashJournal?.begin?.('Receiving','reconcile',{inboundId:t.id,poId:t.poId});const received=[],exceptions=[];(t.items||[]).forEach((item,i)=>{const ordered=num(item.qty),raw=prompt('Received quantity for '+(item.description||('Item '+(i+1)))+'\nOrdered: '+ordered, String(ordered));if(raw===null)return;const qty=Math.max(0,num(raw));const damaged=confirm('Any damaged quantity for '+(item.description||('Item '+(i+1)))+'?');let damagedQty=0;if(damaged)damagedQty=Math.max(0,num(prompt('Damaged quantity', '0')));received.push({...item,orderedQty:ordered,receivedQty:qty,damagedQty});if(qty<ordered)exceptions.push({type:'Backorder',itemId:item.id||'',description:item.description||'',qty:ordered-qty});if(damagedQty>0)exceptions.push({type:'Damage',itemId:item.id||'',description:item.description||'',qty:damagedQty})});const prev=t.status;t.receivedItems=received;t.exceptions=exceptions;t.receivedAt=new Date().toISOString();const back=exceptions.some(x=>x.type==='Backorder'),damage=exceptions.some(x=>x.type==='Damage');t.status=back?'Partially Received':damage?'Exception Review':'Ready';window.RUNLUUniversalAudit?.log('Receiving',t.id,'reconcile',prev,t.status,{poId:t.poId,poNumber:t.poNumber,backorders:exceptions.filter(x=>x.type==='Backorder').length,damages:exceptions.filter(x=>x.type==='Damage').length});save(xs);if(tx)window.RUNLUUniversalCrashJournal.commit(tx.id);render()}
function render(){const host=document.getElementById('universalInbound');if(!host)return;const xs=syncPOs().sort((a,b)=>String(a.requestedDate||'9999').localeCompare(String(b.requestedDate||'9999')));host.innerHTML='<div class="card"><h2>Pickup / Receiving</h2><p class="muted">Ordered vs Received · partial receiving · backorder · damage / exception.</p></div><div class="card">'+(xs.length?xs.map(t=>{const ex=t.exceptions||[];return '<div class="uInbound"><div><b>'+(t.poNumber?'#'+esc(t.poNumber):'PO Draft')+' · '+esc(t.supplier)+'</b><span>'+esc(t.customerName||'Stock')+' · '+esc(t.status)+(ex.length?' · '+ex.length+' exception(s)':'')+'</span></div><select data-fulfill="'+t.id+'"><option'+(t.fulfillment==='Pickup'?' selected':'')+'>Pickup</option><option'+(t.fulfillment==='Supplier Delivery'?' selected':'')+'>Supplier Delivery</option></select><input type="date" data-date="'+t.id+'" value="'+esc(t.requestedDate||'')+'"><button data-receive="'+t.id+'">Receive / Reconcile</button><div class="uReceiveDetail">'+((t.receivedItems||[]).map(x=>'<span>'+esc(x.description||'Item')+': '+esc(x.receivedQty)+' / '+esc(x.orderedQty)+(num(x.damagedQty)?' · damaged '+esc(x.damagedQty):'')+'</span>').join(''))+(ex.map(x=>'<strong>'+esc(x.type)+': '+esc(x.description)+' · '+esc(x.qty)+'</strong>').join(''))+'</div></div>'}).join(''):'<p class="muted">No supplier POs to receive.</p>')+'</div>';
 host.querySelectorAll('[data-fulfill]').forEach(e=>e.onchange=()=>patch(e.dataset.fulfill,x=>x.fulfillment=e.value));host.querySelectorAll('[data-date]').forEach(e=>e.onchange=()=>patch(e.dataset.date,x=>x.requestedDate=e.value));host.querySelectorAll('[data-receive]').forEach(e=>e.onclick=()=>receive(e.dataset.receive));
}
window.RUNLUUniversalInbound=Object.freeze({render,tasks});
})();