(()=>{
const TITLES={"01":{"en":"NOVEMBER 20","zh":"十一月二十日","fr":"20 NOVEMBRE","es":"20 DE NOVIEMBRE"},"02":{"en":"TWO TRAIN TICKETS","zh":"两张车票","fr":"DEUX BILLETS DE TRAIN","es":"DOS BILLETES DE TREN"},"03":{"en":"THE OLD CASE NUMBER","zh":"旧案编号","fr":"L’ANCIEN NUMÉRO DE DOSSIER","es":"EL ANTIGUO NÚMERO DE CASO"},"04":{"en":"THE WAREHOUSE","zh":"那个仓库","fr":"L’ENTREPÔT","es":"EL ALMACÉN"},"05":{"en":"THE TIME GAP","zh":"时间差","fr":"L’ÉCART DE TEMPS","es":"EL DESFASE TEMPORAL"},"06":{"en":"ONE WOMAN, THREE PLACES","zh":"一个女人，三个位置","fr":"UNE FEMME, TROIS ENDROITS","es":"UNA MUJER, TRES LUGARES"},"07":{"en":"GASOLINE","zh":"汽油","fr":"ESSENCE","es":"GASOLINA"},"08":{"en":"THE ACCESS CARD","zh":"门禁卡","fr":"LA CARTE D’ACCÈS","es":"LA TARJETA DE ACCESO"},"09":{"en":"NOT HER","zh":"不是她","fr":"CE N’ÉTAIT PAS ELLE","es":"NO ERA ELLA"},"10":{"en":"THE SECOND NAME","zh":"第二个名字","fr":"LE DEUXIÈME NOM","es":"EL SEGUNDO NOMBRE"}};
const BOOK={en:'All the Evidence Was There',zh:'错序：所有证据都在',fr:'Toutes les preuves étaient là',es:'Todas las pruebas estaban allí'};
const article=document.getElementById('book-content'),title=document.getElementById('chapter-title'),meta=document.getElementById('chapter-meta'),book=document.getElementById('book-title'),nav=document.getElementById('reader-nav');
const q=new URLSearchParams(location.search);let key=q.get('chapter')||'01';if(!TITLES[key])key='01';
const cache={};let request=0;
function lang(){const d=document.documentElement.dataset.runluLanguage;if(['en','zh','fr','es'].includes(d))return d;try{const s=localStorage.getItem('runlu_site_language');if(['en','zh','fr','es'].includes(s))return s}catch(e){}return'en'}
async function jsonFile(path){const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function b64File(path){const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error(`${path}: ${r.status}`);const raw=(await r.text()).trim();const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
async function data(){if(cache[key])return cache[key];let a,b;if(key==='08'){[a,b]=await Promise.all([b64File(`data/${key}-a.b64`),b64File(`data/${key}-b.b64`)])}else{[a,b]=await Promise.all([jsonFile(`data/${key}-a.json`),jsonFile(`data/${key}-b.json`)])}return cache[key]={...a,...b}}
function renderBody(lines){article.replaceChildren(...lines.map((text,i)=>{const p=document.createElement('p');p.textContent=text;if(i===0)p.className='first';return p}))}
function renderError(l){const msg={en:'This chapter is being synchronized. Please try again shortly.',zh:'本章正在同步，请稍后再试。',fr:'Ce chapitre est en cours de synchronisation. Réessayez dans un instant.',es:'Este capítulo se está sincronizando. Vuelve a intentarlo en unos instantes.'}[l];renderBody([msg])}
function makeNav(l){nav.replaceChildren();const n=Number(key),labels={en:['Previous','Next'],zh:['上一章','下一章'],fr:['Précédent','Suivant'],es:['Anterior','Siguiente']}[l];if(n>1){const k=String(n-1).padStart(2,'0'),a=document.createElement('a');a.href=`read.html?chapter=${k}`;a.innerHTML=`<small>${labels[0]}</small><strong>${TITLES[k][l]}</strong>`;nav.appendChild(a)}if(n<10){const k=String(n+1).padStart(2,'0'),a=document.createElement('a');a.className='next';a.href=`read.html?chapter=${k}`;a.innerHTML=`<small>${labels[1]}</small><strong>${TITLES[k][l]}</strong>`;nav.appendChild(a)}}
async function sync(){const id=++request,l=lang();title.textContent=TITLES[key][l];book.textContent=BOOK[l];meta.textContent={en:`CHAPTER ${Number(key)} · RUNLU ORIGINAL`,zh:`第${Number(key)}章 · 润庐原创`,fr:`CHAPITRE ${Number(key)} · ORIGINAL RUNLU`,es:`CAPÍTULO ${Number(key)} · ORIGINAL RUNLU`}[l];makeNav(l);try{const d=await data();if(id===request)renderBody(d[l]||d.en)}catch(e){console.warn('RUNLU evidence reader',e);if(id===request)renderError(l)}}
sync();window.addEventListener('runlu:languagechange',sync);window.addEventListener('pageshow',sync);
})();